# -*- coding: utf-8 -*-
"""model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13ZWCCkHFGO_rDPdtspVuzRqgvknevMnM
"""

import torch
import torch.nn as nn

# Shared MLP architecture used across all regularization experiments
class AblationMLP(nn.Module):
    def __init__(
        self,
        input_dim: int = 3072,
        num_classes: int = 10,
        hidden_sizes=None,
        use_dropout: bool = False,
        dropout_p: float = 0.5,
        use_batchnorm: bool = False
    ):
        super().__init__()

        # Default hidden layer sizes for the baseline model
        if hidden_sizes is None:
            hidden_sizes = [1024, 512, 256]

        # Flatten CIFAR-10 images from [B, 3, 32, 32] to [B, 3072]
        self.flatten = nn.Flatten()

        # First fully connected block
        self.fc1 = nn.Linear(input_dim, hidden_sizes[0])
        self.bn1 = nn.BatchNorm1d(hidden_sizes[0]) if use_batchnorm else nn.Identity()
        self.relu1 = nn.ReLU()
        self.drop1 = nn.Dropout(dropout_p) if use_dropout else nn.Identity()

        # Second fully connected block
        self.fc2 = nn.Linear(hidden_sizes[0], hidden_sizes[1])
        self.bn2 = nn.BatchNorm1d(hidden_sizes[1]) if use_batchnorm else nn.Identity()
        self.relu2 = nn.ReLU()
        self.drop2 = nn.Dropout(dropout_p) if use_dropout else nn.Identity()

        # Third fully connected block
        self.fc3 = nn.Linear(hidden_sizes[1], hidden_sizes[2])
        self.bn3 = nn.BatchNorm1d(hidden_sizes[2]) if use_batchnorm else nn.Identity()
        self.relu3 = nn.ReLU()
        self.drop3 = nn.Dropout(dropout_p) if use_dropout else nn.Identity()

        # Final classification layer (outputs raw logits)
        self.fc4 = nn.Linear(hidden_sizes[2], num_classes)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        # Flatten the input image
        x = self.flatten(x)

        # Apply first block
        x = self.fc1(x)
        x = self.bn1(x)
        x = self.relu1(x)
        x = self.drop1(x)

        # Apply second block
        x = self.fc2(x)
        x = self.bn2(x)
        x = self.relu2(x)
        x = self.drop2(x)

        # Apply third block
        x = self.fc3(x)
        x = self.bn3(x)
        x = self.relu3(x)
        x = self.drop3(x)

        # Output raw class scores
        x = self.fc4(x)
        return x