# -*- coding: utf-8 -*-
"""data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xEKaLKKBodzijjpoJeyukPTpnS4uht9Q
"""

import os
import numpy as np
from torch.utils.data import DataLoader, Subset
from torchvision import datasets, transforms

# CIFAR-10 normalization statistics
CIFAR10_MEAN = (0.4914, 0.4822, 0.4465)
CIFAR10_STD = (0.2023, 0.1994, 0.2010)

# Define the common preprocessing pipeline
def get_transforms():
    return transforms.Compose([
        transforms.ToTensor(),
        transforms.Normalize(CIFAR10_MEAN, CIFAR10_STD)
    ])

# Create the fixed split once, or load it if it already exists
def create_or_load_fixed_split(
    split_path: str = "splits/fixed_cifar10_split.npz",
    subset_size: int = 20000,
    train_size: int = 15000,
    val_size: int = 5000,
    seed: int = 42
):
    if train_size + val_size != subset_size:
        raise ValueError("train_size + val_size must equal subset_size")

    os.makedirs(os.path.dirname(split_path), exist_ok=True)

    if os.path.exists(split_path):
        split_data = np.load(split_path)
        train_idx = split_data["train_idx"]
        val_idx = split_data["val_idx"]
        return train_idx, val_idx

    rng = np.random.default_rng(seed)
    all_indices = np.arange(50000)
    rng.shuffle(all_indices)

    subset_indices = all_indices[:subset_size]
    train_idx = subset_indices[:train_size]
    val_idx = subset_indices[train_size:train_size + val_size]

    np.savez(split_path, train_idx=train_idx, val_idx=val_idx)
    return train_idx, val_idx

# Load the full CIFAR-10 train and test datasets
def get_datasets(data_root: str = "./data"):
    transform = get_transforms()

    full_train_dataset = datasets.CIFAR10(
        root=data_root,
        train=True,
        download=True,
        transform=transform
    )

    test_dataset = datasets.CIFAR10(
        root=data_root,
        train=False,
        download=True,
        transform=transform
    )

    return full_train_dataset, test_dataset

# Build dataloaders using the fixed train / validation split
def get_dataloaders(
    data_root: str = "./data",
    split_path: str = "splits/fixed_cifar10_split.npz",
    subset_size: int = 20000,
    train_size: int = 15000,
    val_size: int = 5000,
    batch_size: int = 128,
    seed: int = 42,
    num_workers: int = 2
):
    full_train_dataset, test_dataset = get_datasets(data_root=data_root)

    train_idx, val_idx = create_or_load_fixed_split(
        split_path=split_path,
        subset_size=subset_size,
        train_size=train_size,
        val_size=val_size,
        seed=seed
    )

    train_dataset = Subset(full_train_dataset, train_idx)
    val_dataset = Subset(full_train_dataset, val_idx)

    train_loader = DataLoader(
        train_dataset,
        batch_size=batch_size,
        shuffle=True,
        num_workers=num_workers
    )

    val_loader = DataLoader(
        val_dataset,
        batch_size=batch_size,
        shuffle=False,
        num_workers=num_workers
    )

    test_loader = DataLoader(
        test_dataset,
        batch_size=batch_size,
        shuffle=False,
        num_workers=num_workers
    )

    return train_loader, val_loader, test_loader