# -*- coding: utf-8 -*-
"""early_stopping.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pl9BuYiC-ThcvJOjsYXKfxduBodAa71d
"""

from copy import deepcopy

# Utility class for stopping training when validation loss stops improving
class EarlyStopping:
    def __init__(self, patience: int = 5, min_delta: float = 1e-4):
        # Number of epochs to wait after the last improvement
        self.patience = patience

        # Minimum improvement required to reset the counter
        self.min_delta = min_delta

        # Best validation loss seen so far
        self.best_loss = float("inf")

        # Number of consecutive epochs without improvement
        self.counter = 0

        # Best model weights saved during training
        self.best_state = None

        # Epoch index of the best validation loss
        self.best_epoch = 0

    def step(self, val_loss: float, model, epoch: int) -> bool:
        # Check whether validation loss improved enough
        improved = val_loss < (self.best_loss - self.min_delta)

        if improved:
            self.best_loss = val_loss
            self.counter = 0
            self.best_state = deepcopy(model.state_dict())
            self.best_epoch = epoch
            return False

        # Increment the counter if no improvement occurred
        self.counter += 1

        # Stop training if patience is exceeded
        return self.counter >= self.patience