# -*- coding: utf-8 -*-
"""plots.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zCyL4bIpDJeGqUpNX-omQ1um8SiFDuYl
"""

import os
import matplotlib.pyplot as plt
import pandas as pd

# Create the output directory if it does not already exist
def ensure_dir(path: str):
    os.makedirs(path, exist_ok=True)

# Plot train, validation, and test loss curves
def plot_loss_curves(result, save_path=None, show=True):
    history = result["history"]
    epochs = range(1, len(history["train_loss"]) + 1)

    plt.figure(figsize=(8, 5))
    plt.plot(epochs, history["train_loss"], label="Train Loss")
    plt.plot(epochs, history["val_loss"], label="Validation Loss")
    plt.plot(epochs, history["test_loss"], label="Test Loss")
    plt.xlabel("Epoch")
    plt.ylabel("Loss")
    plt.title(f'{result["name"]} - Loss Curves')
    plt.legend()
    plt.grid(True)
    plt.tight_layout()

    if save_path is not None:
        ensure_dir(os.path.dirname(save_path))
        plt.savefig(save_path, bbox_inches="tight")

    if show:
        plt.show()
    else:
        plt.close()

# Plot train, validation, and test accuracy curves
def plot_accuracy_curves(result, save_path=None, show=True):
    history = result["history"]
    epochs = range(1, len(history["train_acc"]) + 1)

    plt.figure(figsize=(8, 5))
    plt.plot(epochs, history["train_acc"], label="Train Accuracy")
    plt.plot(epochs, history["val_acc"], label="Validation Accuracy")
    plt.plot(epochs, history["test_acc"], label="Test Accuracy")
    plt.xlabel("Epoch")
    plt.ylabel("Accuracy (%)")
    plt.title(f'{result["name"]} - Accuracy Curves')
    plt.legend()
    plt.grid(True)
    plt.tight_layout()

    if save_path is not None:
        ensure_dir(os.path.dirname(save_path))
        plt.savefig(save_path, bbox_inches="tight")

    if show:
        plt.show()
    else:
        plt.close()

# Plot the generalization gap using train-validation and train-test differences
def plot_generalization_gap(result, save_path=None, show=True):
    history = result["history"]
    epochs = range(1, len(history["train_acc"]) + 1)

    gap_val = [
        train - val
        for train, val in zip(history["train_acc"], history["val_acc"])
    ]

    gap_test = [
        train - test
        for train, test in zip(history["train_acc"], history["test_acc"])
    ]

    plt.figure(figsize=(8, 5))
    plt.plot(epochs, gap_val, label="Train - Validation Gap")
    plt.plot(epochs, gap_test, label="Train - Test Gap")
    plt.xlabel("Epoch")
    plt.ylabel("Gap (%)")
    plt.title(f'{result["name"]} - Generalization Gap')
    plt.legend()
    plt.grid(True)
    plt.tight_layout()

    if save_path is not None:
        ensure_dir(os.path.dirname(save_path))
        plt.savefig(save_path, bbox_inches="tight")

    if show:
        plt.show()
    else:
        plt.close()

# Plot cross-entropy loss and explicit L2 term for experiments that use explicit L2
def plot_ce_and_l2(result, save_path=None, show=True):
    history = result["history"]
    epochs = range(1, len(history["train_ce_loss"]) + 1)

    plt.figure(figsize=(8, 5))
    plt.plot(epochs, history["train_ce_loss"], label="Train CE Loss")
    plt.plot(epochs, history["train_l2_term"], label="Train L2 Term")
    plt.xlabel("Epoch")
    plt.ylabel("Value")
    plt.title(f'{result["name"]} - CE Loss and L2 Term')
    plt.legend()
    plt.grid(True)
    plt.tight_layout()

    if save_path is not None:
        ensure_dir(os.path.dirname(save_path))
        plt.savefig(save_path, bbox_inches="tight")

    if show:
        plt.show()
    else:
        plt.close()

# Generate all available plots for a given experiment result
def plot_all_curves(result, save_dir=None, show=True):
    safe_name = (
        result["name"]
        .lower()
        .replace(" ", "_")
        .replace("+", "plus")
        .replace("(", "")
        .replace(")", "")
    )

    loss_path = None
    acc_path = None
    gap_path = None
    ce_l2_path = None

    if save_dir is not None:
        loss_path = os.path.join(save_dir, f"{safe_name}_loss.png")
        acc_path = os.path.join(save_dir, f"{safe_name}_accuracy.png")
        gap_path = os.path.join(save_dir, f"{safe_name}_gap.png")
        ce_l2_path = os.path.join(save_dir, f"{safe_name}_ce_l2.png")

    plot_loss_curves(result, save_path=loss_path, show=show)
    plot_accuracy_curves(result, save_path=acc_path, show=show)
    plot_generalization_gap(result, save_path=gap_path, show=show)

    if sum(result["history"]["train_l2_term"]) > 0:
        plot_ce_and_l2(result, save_path=ce_l2_path, show=show)

# Convert a single experiment result into one summary row
def make_summary_row(result):
    row = {
        "Experiment": result["name"],
        "Final Train Loss": round(result["final_train_loss"], 4),
        "Final Val Loss": round(result["final_val_loss"], 4),
        "Final Test Loss": round(result["final_test_loss"], 4),
        "Final Train Acc": round(result["final_train_acc"], 2),
        "Final Val Acc": round(result["final_val_acc"], 2),
        "Final Test Acc": round(result["final_test_acc"], 2),
        "Gap (Train-Val)": round(result["generalization_gap_val"], 2),
        "Gap (Train-Test)": round(result["generalization_gap_test"], 2),
    }

    if "best_epoch" in result:
        row["Best Epoch"] = result["best_epoch"]

    if "best_val_loss" in result:
        row["Best Val Loss"] = round(result["best_val_loss"], 4)

    if "used_explicit_l2" in result:
        row["Explicit L2"] = result["used_explicit_l2"]

    if "weight_decay_or_lambda" in result:
        row["Lambda / Weight Decay"] = result["weight_decay_or_lambda"]

    return row

# Build a summary table from all experiment results
def make_summary_table(results_dict):
    rows = [make_summary_row(res) for res in results_dict.values()]
    return pd.DataFrame(rows)

# Save the summary table to a CSV file
def save_summary_table(df, save_path: str):
    ensure_dir(os.path.dirname(save_path))
    df.to_csv(save_path, index=False)

# Plot all experiments against the baseline on the same figure
def plot_all_experiments_vs_baseline(results, metric_key, ylabel, title, save_path=None, gap_mode=False, show=True):
    plt.figure(figsize=(10, 6))

    order = [
        "baseline",
        "dropout",
        "early_stopping",
        "batchnorm",
        "dropout_batchnorm",
        "l2_dropout"
    ]

    for key in order:
        result = results[key]

        if gap_mode:
            values = [
                train - val
                for train, val in zip(result["history"]["train_acc"], result["history"]["val_acc"])
            ]
        else:
            values = result["history"][metric_key]

        epochs = range(1, len(values) + 1)

        if key == "baseline":
            plt.plot(epochs, values, label=result["name"], linewidth=3)
        else:
            plt.plot(epochs, values, label=result["name"], linestyle="--")

    plt.xlabel("Epoch")
    plt.ylabel(ylabel)
    plt.title(title)
    plt.legend()
    plt.grid(True)
    plt.tight_layout()

    if save_path is not None:
        ensure_dir(os.path.dirname(save_path))
        plt.savefig(save_path, bbox_inches="tight")

    if show:
        plt.show()
    else:
        plt.close()